core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.PostListView.as_view(), name='list'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return "/" + str(self.id) + "/"

    class Meta:
        ordering = ["-id"]

posts/views.py
from django.shortcuts import render
from django.views import generic
from .models import Post
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy

class PostListView(generic.ListView):
    model = Post
    template_name = 'list.html'
    context_object_name = 'posts'

class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'detail.html'
    context_object_name = 'post'

class PostCreateView(LoginRequiredMixin, generic.CreateView):
    model = Post
    template_name = 'create.html'
    fields = ['title', 'body']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("posts:detail", kwargs={'pk': self.object.pk})

    def get_form(self, form_class=None):
        form = super().get_form(form_class)

        form.fields['title'].widget.attrs['class'] = 'form-control'
        form.fields['title'].widget.attrs['placeholder'] = 'Title'
        form.fields['title'].label = ''

        form.fields['body'].widget.attrs['class'] = 'form-control'
        form.fields['body'].widget.attrs['placeholder'] = 'Body'
        form.fields['body'].label = ''

        return form


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Post
    template_name = 'update.html'
    context_object_name = 'post'
    fields = ['title', 'body']

    def test_func(self):
        post_object = self.get_object()
        user = self.request.user
        if user == post_object.author:
            return True
        else:
            return False

    def get_success_url(self):
        return reverse_lazy("posts:detail", kwargs={'pk': self.object.pk})
    
    def get_form(self, form_class=None):
        form = super().get_form(form_class)

        form.fields['title'].widget.attrs['class'] = 'form-control'
        form.fields['title'].label = ''
        form.fields['title'].widget.attrs['placeholder'] = 'Title'

        form.fields['body'].widget.attrs['class'] = 'form-control'
        form.fields['body'].label = ''
        form.fields['body'].widget.attrs['placeholder'] = 'Body'

        return form
    

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Post
    template_name = 'delete.html'
    context_object_name = 'post'

    success_url = '/'

    def test_func(self):
        post_object = self.get_object()
        user = self.request.user
        if user == post_object.author:
            return True
        else:
            return False
        

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport"
	      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
	<title>{% block title %}{% endblock %}</title>
</head>
<body>
	<nav class="navbar shadow navbar-expand-lg navbar-dark bg-dark">
		<div class="container">
			<a href="/" class="navbar-brand">Blog</a>
			<div class="navbar-collapse" id="navbarNav">
				<ul class="navbar-nav">
					<li class="nav-item">
						<a href="/" class="nav-link active" aria-current="page">Main Page</a>
					</li>

					{% if user.is_authenticated %}
						<li class="nav-item">
							<a href="{% url 'posts:create' %}" class="nav-link">Write New Post</a>
						</li>
					{% endif %}
				</ul>
			</div>
		</div>
	</nav>

	<div class="container">{% block content %}{% endblock %}</div>

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
</body>
</html>

templates/create.html
{% extends 'base.html' %}

{% block title %}
	create a post
{% endblock %}

{% block content %}
	<h2 class="mt-3">Create a Post</h2>

	<div class="card mt-3">
		<div class="card-body">
			<form action="" method="POST">
				{% csrf_token %}
				{{ form.as_p }}
				<button class="btn btn-primary" type="submit">Submit</button>
			</form>
		</div>
	</div>
{% endblock %}

templates/delete.html
{% extends 'base.html' %}

{% block title %}
	Delete - {{ post.title }}
{% endblock %}

{% block content %}
	<h2 class="mt-3">Delete - {{ post.title }}</h2>

	<div class="card mt-3">
		<div class="card-body">
			<form action="" method="POST">
				{% csrf_token %}
				<p>Do you want to delete this item?</p>
				<button class="btn btn-danger" type="submit">Delete</button>
				<a href="/" class="btn btn-primary">Back to homepage</a>
			</form>
		</div>
	</div>
{% endblock %}

templates/detail.html
{% extends 'base.html' %}

{% block title %}
	{{ post.title }}
{% endblock %}

{% block content %}
	<h2 class="mt-3">{{ post.title }}</h2>

	<div class="card mt-3">
		<div class="card-body">
			<b>{{ post.body }}</b>
			<p><small class="text-muted"><i>Posted at: {{ post.created }} | Author: {{ post.author }}</i></small></p>
			{% if post.author == request.user %}
				<small class="text-muted">
					<a href="{% url 'posts:update' post.id %}" class="btn btn-primary">Update</a>
					<a href="{% url 'posts:delete' post.id %}" class="btn btn-danger">Delete</a>
					<a href="/" class="btn btn-secondary">Back to Home</a>
				</small>
			{% endif %}
		</div>
	</div>
{% endblock %}

templates/list.html
{% extends 'base.html' %}

{% block title %}
    Main page
{% endblock %}

{% block content %}
    <h2 class="mt-3">Latest Posts</h2>
    <div class="card">
        {% for post in posts %}
            <div class="card mt-3">
                <div class="card-body">
                    {{ post.title }}... <small> <a href="{{ post.get_absolute_url }}">Read more</a> </small>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/update.html
{% extends 'base.html' %}

{% block title %}
	Edit - {{ post.title }}
{% endblock %}

{% block content %}
	<h2 class="mt-3">Edit - {{ post.title }}</h2>

	<div class="card mt-3">
		<div class="card-body">
			<form action="" method="POST">
				{% csrf_token %}
				{{ form.as_p }}
				<button class="btn btn-primary" type="submit">Update</button>
			</form>
		</div>
	</div>
{% endblock %}